GERONIMO-4093 Enhance GShell based scripts to use setjavaenv for determining the Java runtime, allow users to continue to supply a setenv script and updated the Unix gsh script with some missing Cygwin, OS400 and error checking that was in geronimo.sh.
git-svn-id: https://svn.apache.org/repos/asf/geronimo/server/trunk@665749 13f79535-47bb-0310-9956-ffa450edef68

diff --git a/assemblies/geronimo-boilerplate/src/main/underlay/bin/gsh b/assemblies/geronimo-boilerplate/src/main/underlay/bin/gsh
--- a/assemblies/geronimo-boilerplate/src/main/underlay/bin/gsh
+++ b/assemblies/geronimo-boilerplate/src/main/underlay/bin/gsh
@@ -22,35 +22,83 @@
 ## $Rev: 539227 $ $Date: 2007-05-17 19:48:49 -0700 (Thu, 17 May 2007) $
 ##
 
-DIRNAME=`dirname "$0"`
-
 # OS specific support (must be 'true' or 'false').
 cygwin=false
+os400=false
 case "`uname`" in
-    CYGWIN*)
-        cygwin=true
-        ;;
+CYGWIN*) cygwin=true;;
+OS400*) os400=true;;
 esac
 
-# For Cygwin, ensure paths are in UNIX format before anything is touched
-if $cygwin ; then
-    [ -n "$GSHELL_HOME" ] && GSHELL_HOME=`cygpath --unix "$GSHELL_HOME"`
-    [ -n "$JAVACMD" ] && JAVACMD=`cygpath --unix "$JAVACMD"`
-    [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
-fi
+# resolve links - $0 may be a softlink
+PRG="$0"
+
+while [ -h "$PRG" ]; do
+    ls=`ls -ld "$PRG"`
+    link=`expr "$ls" : '.*-> \(.*\)$'`
+    if expr "$link" : '/.*' > /dev/null; then
+        PRG="$link"
+    else
+        PRG=`dirname "$PRG"`/"$link"
+    fi
+done
+
+PRGDIR=`dirname "$PRG"`
 
 # Locate GSHELL_HOME if not it is not set
 if [ "x$GSHELL_HOME" = "x" ]; then
-    GSHELL_HOME=`cd "$DIRNAME/.."; pwd`
+    GSHELL_HOME=`cd "$PRGDIR/.."; pwd`
 fi
 
-# Determine the Java command to use to start the JVM
-if [ -z "$JAVACMD" ]; then
-    if [ -n "$JAVA_HOME" ]; then
-        JAVACMD="$JAVA_HOME/bin/java"
+# Execute optional environment  if provided by the user
+if [ -r "$GSHELL_HOME"/bin/setenv.sh ]; then
+    . "$GSHELL_HOME"/bin/setenv.sh
+fi
+
+# For Cygwin, ensure paths are in UNIX format before anything is touched
+if $cygwin ; then
+    [ -n "$JRE_HOME" ] && JRE_HOME=`cygpath --unix "$JRE_HOME"`
+    [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
+    [ -n "$GSHELL_HOME" ] && GSHELL_HOME=`cygpath --unix "$GSHELL_HOME"`
+fi
+
+# For OS400
+if $os400; then
+    # Set job priority to standard for interactive (interactive - 6) by using
+    # the interactive priority - 6, the helper threads that respond to requests
+    # will be running at the same priority as interactive jobs.
+    COMMAND='chgjob job('$JOBNAME') runpty(6)'
+    system $COMMAND
+    # Enable multi threading
+    export QIBM_MULTI_THREADED=Y
+fi
+
+# Get standard Java environment variables
+# (based upon Tomcat's setclasspath.sh but renamed since Geronimo's classpath
+# is set in the JAR manifest)
+if $os400; then
+    # -r will Only work on the os400 if the files are:
+    # 1. owned by the user
+    # 2. owned by the PRIMARY group of the user
+    # this will not work if the user belongs in secondary groups
+    BASEDIR="$GSHELL_HOME"
+    . "$GSHELL_HOME"/bin/setjavaenv.sh
+else
+    if [ -r "$GSHELL_HOME"/bin/setjavaenv.sh ]; then
+        BASEDIR="$GSHELL_HOME"
+        . "$GSHELL_HOME"/bin/setjavaenv.sh
     else
-        JAVACMD="java"
+        echo "Cannot find $GSHELL_HOME/bin/setjavaenv.sh"
+        echo "This file is needed to run this program"
+        exit 1
     fi
+fi
+
+# For Cygwin, switch paths to Windows format before running java
+if $cygwin ; then
+    JAVA_HOME=`cygpath --absolute --windows "$JAVA_HOME"`
+    JRE_HOME=`cygpath --absolute --windows "$JRE_HOME"`
+    GSHELL_HOME=`cygpath --absolute --windows "$GSHELL_HOME"`
 fi
 
 BOOTJAR="$GSHELL_HOME/lib/boot/gshell-bootstrap.jar"
@@ -59,5 +107,5 @@ if $cygwin ; then
 fi
 
 # Start the JVM
-exec "$JAVACMD" $JAVA_OPTS -jar "$BOOTJAR" "$@"
+exec "$_RUNJAVA" $JAVA_OPTS -jar "$BOOTJAR" "$@"
 
diff --git a/assemblies/geronimo-boilerplate/src/main/underlay/bin/start-server b/assemblies/geronimo-boilerplate/src/main/underlay/bin/start-server
--- a/assemblies/geronimo-boilerplate/src/main/underlay/bin/start-server
+++ b/assemblies/geronimo-boilerplate/src/main/underlay/bin/start-server
@@ -22,7 +22,61 @@
 ## $Rev: 539227 $ $Date: 2007-05-17 19:48:49 -0700 (Thu, 17 May 2007) $
 ##
 
-DIRNAME=`dirname "$0"`
+# --------------------------------------------------------------------
+# Startup script for Geronimo that starts Geronimo in the foreground.
+#
+# This script calls the gsh script passing "geronimo/start-server" as the
+# first argument followed by the arguments supplied by the caller.
+#
+# Alternatively you can use the more comprehensive gsh interface directly.
+#
+# Invocation Syntax:
+#
+#   start-server [geronimo_args ...]
+#
+# Environment Variable Prequisites:
+#
+#   Refer to the documentation in the gsh file for information
+#   on environment variables etc.
+#
+# --------------------------------------------------------------------
+
+os400=false
+case "`uname`" in
+CYGWIN*) cygwin=true;;
+OS400*) os400=true;;
+esac
+
+# resolve links - $0 may be a softlink
+PRG="$0"
+
+while [ -h "$PRG" ] ; do
+  ls=`ls -ld "$PRG"`
+  link=`expr "$ls" : '.*-> \(.*\)$'`
+  if expr "$link" : '/.*' > /dev/null; then
+    PRG="$link"
+  else
+    PRG=`dirname "$PRG"`/"$link"
+  fi
+done
+
+PRGDIR=`dirname "$PRG"`
+EXECUTABLE=gsh
+
+# Check that target executable exists
+if $os400; then
+  # -x will Only work on the os400 if the files are:
+  # 1. owned by the user
+  # 2. owned by the PRIMARY group of the user
+  # this will not work if the user belongs in secondary groups
+  eval
+else
+  if [ ! -x "$PRGDIR"/"$EXECUTABLE" ]; then
+    echo "Cannot find $PRGDIR/$EXECUTABLE"
+    echo "This file is needed to run this program"
+    exit 1
+  fi
+fi
 
 ARGS=
 while [ $# -ge 1 ]; do
@@ -30,5 +84,5 @@ while [ $# -ge 1 ]; do
   shift
 done
 
-exec "$DIRNAME/gsh" -c "geronimo/start-server $ARGS"
+exec "$PRGDIR"/"$EXECUTABLE" -c "geronimo/start-server $ARGS"
 
